// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcedrlYLz4iQJ-a-qCxsTapqw7OT6ZNSE',
    appId: '1:329537539737:android:61e1d9b4feb8bef907f208',
    messagingSenderId: '329537539737',
    projectId: 'crudtutorial-5f675',
    storageBucket: 'crudtutorial-5f675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZM67pqk7uA9s46MyC3-1Uie59LJQAYtg',
    appId: '1:329537539737:ios:54da176166a3b34b07f208',
    messagingSenderId: '329537539737',
    projectId: 'crudtutorial-5f675',
    storageBucket: 'crudtutorial-5f675.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRVaI016Z72d9cMW05BujWpAACZqWqSs',
    appId: '1:329537539737:web:37d7e1d585d5212407f208',
    messagingSenderId: '329537539737',
    projectId: 'crudtutorial-5f675',
    authDomain: 'crudtutorial-5f675.firebaseapp.com',
    storageBucket: 'crudtutorial-5f675.appspot.com',
  );

}